### ISSUE TITLE
usemin throws warning for default configuration

### ISSUE THREAD

**Issue by nerdgore** [yeoman/grunt-usemin#300] opened 2014-02-19 08:21 UTC
Starting with version 2.0.0 I can't get grunt-usemin to work at all. If I pass in a valid path to an html file I get this template warning 100% of the time. I produced a small test case to rule out any issues inside my (rather large) html file but I had no success.

> Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Use --force to continue.

Consequently downgrading to version 0.1.13 finally solved the issue.

### Test case:

```js
config.useminPrepare = {
        options: {
            root: "src/main/webapp/",
            dest: "target/<%= pkg.name %>/"
        },
        html: "src/main/webapp/test.html"
    };
```

```html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>title</title>
</head>
<body>
    <!-- build:js js/app.js -->
    <script src="js/app/views/sesresult.view.js" type="text/javascript"></script>
    <script src="js/app/views/ses.view.js" type="text/javascript"></script>
    <!-- endbuild -->
    
</body>
</html>
```

#### Output for 0.0.13:
```sh
grunt useminPrepare
Running "useminPrepare:html" (useminPrepare) task
Going through src/main/webapp/test.html to update the config
Looking for build script HTML comment blocks

Found a block:
    <!-- build:js js/app.js -->

    <script src="js/app/views/sesresult.view.js" type="text/javascript"></script>
    <script src="js/app/views/ses.view.js" type="text/javascript"></script>

    <!-- endbuild -->
Updating config with the following assets:
    - src/main/webapp/js/app/views/sesresult.view.js
    - src/main/webapp/js/app/views/ses.view.js

Configuration is now:

  cssmin:
  {}

  concat:
  { 'target/mobile-web-client/js/app.js':
   [ 'src/main/webapp/js/app/views/sesresult.view.js',
     'src/main/webapp/js/app/views/ses.view.js' ] }

  uglify:
  { 'target/mobile-web-client/js/app.js': 'target/mobile-web-client/js/app.js' }

  requirejs:
  {}

Done, without errors.
```

#### Output for 2.0.x

```sh
[...]
Running "useminPrepare:prod" (useminPrepare) task
Verifying property useminPrepare.prod exists in config...OK
Files: src/main/webapp/test.html -> target/mobile-web-client/
Options: root="src/main/webapp/"
Going through src/main/webapp/test.html to update the config
Looking for build script HTML comment blocks
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Use --force to continue.

Aborted due to warnings.
```

The question is now: Did something in the api change that I am missing or is this a bug?

**Comment by stephanebachelier** [comment] 2015-03-11 21:53
@nerdgore @hkdobrev it's not related to `grunt-usemin` but to the usage of a template, see my comment in [#291](https://github.com/yeoman/grunt-usemin/issues/291#issuecomment-78379930)

Duplicate of #291.

@nerdgore in your use case make sure that when using `<%= pkg.version %>`, `pkg` is really defined by adding a `pkg` entry in your config with its value set to something like `grunt.file.readJSON('package.json')`

**Closed by stephanebachelier** 2015-03-11 21:53 UTC
