### ISSUE TITLE
blockReplacements strips my css tags of data-* attributes

### ISSUE THREAD

**Issue by daprahamian** [yeoman/grunt-usemin#522] opened 2015-03-04 21:30 UTC
I currently have a bunch of css files with the following:

```html
<!-- build:css out.css -->
<link href="./my/css/file.css" data-my-attribute />
<link href="./my/css/file2.css" data-my-attribute />
<!-- enbuild -->
```

The outputted link tags are stripped of the ```data-my-attribute``` fields, and I have to override blockReplacements in order to get them. Is there a way around this, or do I have to do this by hand? It seems quite cumbersome to have to override blockReplacements just to get one attribute.

**Comment by brunowego** [comment] 2015-03-05 20:08
I think this issue have relation with #523

**Comment by stephanebachelier** [comment] 2015-03-10 23:06
closing as a duplicate of #523

**Closed by stephanebachelier** 2015-03-10 23:06 UTC
