### ISSUE TITLE
Should probably throw an error if the html file referenced in the usemin block cannot be found

### ISSUE THREAD

**Issue by prdonahue** [yeoman/grunt-usemin#494] opened 2014-11-26 06:43 UTC
I made a typo like so:
```
        usemin: {
            html: '%<= btp.dist %>/index.html'
        },
```

And the output to useminPrepare was normal, but I couldn't figure out why my JS and CSS includes weren't getting replaced. Here is the (verbose) output I saw:

```
Running "usemin" task

Running "usemin:html" (usemin) task
Verifying property usemin.html exists in config...OK
Files: [no src] -> html
Options: type="html"
Replaced 0 references to assets
```

I found the bug eventually, but had usemin thrown an error saying it couldn't find/open the file in question (rather than silently saying there was nothing replaced), I'd have been better off -- and assume others would as well.

Anyway, thanks for a great plugin!

**Comment by stephanebachelier** [comment] 2015-02-19 18:18
@prdonahue close this one as it is a duplicate of #452.

**Closed by stephanebachelier** 2015-02-19 18:18 UTC
