### ISSUE TITLE
usemin not working with spaces in target path

### ISSUE THREAD

**Issue by TheRoks** [yeoman/grunt-usemin#379] opened 2014-05-28 11:37 UTC
In my case I want to build to a location with spaces in it. Like this:
&lt;!-- build:js style library/scripts.js -->

However this won't work. I tried all logical space replacements and escapes, none are working. Documentation on this is not available.

Is there a possible solution for this?

**Comment by stephanebachelier** [comment] 2015-02-22 01:32
Duplicate of #512

**Closed by stephanebachelier** 2015-02-22 01:32 UTC
Labels: duplicate
