### ISSUE TITLE
Throw up on missing HTML?

### ISSUE THREAD

**Issue by ain** [yeoman/grunt-usemin#452] opened 2014-10-16 14:59 UTC
I've just spent quite a lot of time understanding what's going on because the preceding `copy:dist` task did not output HTML for `usemin` to work on and `usemin` just fell through silently:
```sh
Running "usemin:html" (usemin) task

Done, without errors.
```
I'd suggest `usemin` throwing up on a target that is not there (at all).

I realise there could be a glob pattern involved, but could we do anything to aid the user towards the issue?

**Comment by arthurvr** [comment] 2015-02-19 17:24
Duplicate of https://github.com/yeoman/grunt-usemin/issues/494, isn't it?

**Comment by ain** [comment] 2015-02-19 17:26
No. #494 is a dupe of this one.

**Comment by arthurvr** [comment] 2015-02-19 17:42
Whoops. Right. Can one close that ticket?

**Comment by stephanebachelier** [comment] 2015-02-19 18:17
@arthurvr which one do you want to close ?

**Comment by stephanebachelier** [comment] 2015-02-19 18:19
@arthurvr closed #494 in favor of this one

**Comment by stephanebachelier** [comment] 2015-02-21 18:33
By the way it should be resolved by #306, but this PR need to be updated as it is too old now.

**Comment by stephanebachelier** [comment] 2015-04-14 00:33
Fixed in `dev` branch

**Closed by stephanebachelier** 2015-04-14 00:33 UTC
Labels: code review
