### ISSUE TITLE
Version 3.0.0 breaks specifying type of a usemin target.

### ISSUE THREAD

**Issue by ArturDorochowicz** [yeoman/grunt-usemin#526] opened 2015-03-16 18:27 UTC
Before the offending change it was possible to specify the type of the target in usemin task configuration, like so:

    usemin: {
      'mytarget': {
        files: { src: '...' },
        options: { type: 'html', ... }
      }
    }

(I think this use was documented somewhere, but I can't seem to find it now.)

Currently the value of the type option is ignored and the target name determines the type, therefore - for instance - there can be only one html target - the one named 'html'.

The breaking change happened:
https://github.com/yeoman/grunt-usemin/blob/989766245ba750b116521c26eca7efbdc22e22c2/tasks/usemin.js

**Comment by stephanebachelier** [comment] 2015-03-18 10:04
@ArturDorochowicz it should be fixed with #524

**Comment by stephanebachelier** [comment] 2015-04-13 21:35
closing as a duplicate of #524.

**Closed by stephanebachelier** 2015-04-13 21:35 UTC
