### ISSUE TITLE
Use an HTML parser to extract blocks

### ISSUE THREAD

**Issue by connec** [yeoman/grunt-usemin#285] opened 2014-01-23 13:00 UTC
The current implementation for parsing blocks from files relies too much on the file being human-generated, requiring anything special to be on a separate line.  Given the usefulness and proliferation of templating engines, many of which quite rightly disregard whitespace, it would be better if file parsing did not depend on non-semantic aspects of HTML structure, like linebreaks.

A streaming parser like fb55/htmlparser2 would offer competitive performance whilst affording much great flexibility.

I'm happy to look at making a pull request for this, assuming it's something the maintainer(s) would consider accepting?

**Comment by arthurvr** [comment] 2015-02-19 16:23
Can somebody close this issue? It's dupe of https://github.com/yeoman/grunt-usemin/issues/244

**Comment by stephanebachelier** [comment] 2015-02-21 16:56
@arthurvr closing.

**Closed by stephanebachelier** 2015-02-21 16:56 UTC
