### ISSUE TITLE
Build pattern regex doesn't support url path with space

### ISSUE THREAD

**Issue by JackZhang1988** [yeoman/grunt-usemin#512] opened 2015-02-10 01:21 UTC
My build comment template in my html like this:
```
<!-- build:css <%- staticBase%>/css/index/index.css -->
<link href="<%- staticBase %>/css/common/base.css<%- version %>" type="text/css" rel="stylesheet">
<link href="<%- staticBase %>/css/index/index.css<%- version %>" type="text/css" rel="stylesheet">
<link href="<%- staticBase %>/css/common/itemListTemplate.css<%- version %>" type="text/css" rel="stylesheet">
<!-- endbuild -->

```

the staticBase variable is the DNSUrl i will render by grunt template, the first line `<!-- build:css <%- staticBase%>/css/index/index.css -->` , you can see there is a space before word `staticBase`, but the usemin build pattern can't parse this pattern.

I check the usemin rebuild pattern is `/<!--\s*build:(\w+)(?:\(([^\)]+)\))?\s*([^\s]+)\s*-->/`, it does't support   build path with a space, when i remove the space before `staticBase` word, it works fine.

**Comment by stephanebachelier** [comment] 2015-02-21 16:33
@JackZhang1988 the problem is that the third group in the regexp, which is `([^\s]+)`, exclude any space.

**Comment by stephanebachelier** [comment] 2015-02-22 00:21
@JackZhang1988 can you test the branch in #516 to see if it fixes your use case. I don't know if it also related to your other issue #513

**Comment by stephanebachelier** [comment] 2015-02-22 00:30
@JackZhang1988 see my comment in your other issue.

**Comment by stephanebachelier** [comment] 2015-04-14 00:42
@JackZhang1988 could you explain why you would want to have your path being variable ?
I need to have more information on your use case.
Seeing that you have `<%- version %>`, I think you're missing the point of usemin whose job is to optimize your page, so it need to know where are your assets.

I'm closing this issue as irrelevant. Feel free to come back with more explanations and reopen if needed.

**Closed by stephanebachelier** 2015-04-14 00:42 UTC
Labels: waiting

**Comment by JackZhang1988** [comment] 2015-10-10 07:09
@stephanebachelier sorry for replaying so late, the variable for path used for static files' CDN path, usually we develop our project in local, this variable will be 'localhost', when our project release to internet, this variable will be the CDN path.

i know there maybe other way to accomplish this, but when i join my team, it has used this way.

**Comment by stephanebachelier** [comment] 2015-10-10 09:38
@JackZhang1988 maybe you should use another plugin that will replace all the paths of the assets, but once usemin have processed your files.
